import exe25
sentence = "All good things come to those who wait."
words = exe25.break_words(sentence)
print("Splited words",words)
sorted_words = exe25.sort_words(words)
print("Sorted words ",sorted_words)
print(type(sorted_words))
print(".......................")
print(words)
exe25.print_first_word(words)
print(words)
print(".......................")
print(words)
exe25.print_last_word(words)
print(words)
print(".......................")
print("Sorted words list")
print(sorted_words)
exe25.print_first_word(sorted_words)
print(sorted_words)
print(".......................")
print(sorted_words)
exe25.print_last_word(sorted_words)
print(sorted_words)
print(".......................")
print("Sentence") 
print(sentence)  
sorted_words = exe25.sort_sentence(sentence)
print("Sorted sentence:-",sorted_words)
exe25.print_first_and_last(sentence)
exe25.print_first_and_last_sorted(sentence)